# Generated by Django 3.0.2 on 2020-03-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketer',
            name='image',
            field=models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic'),
        ),
    ]
