# Generated by Django 3.0.4 on 2020-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0002_cricketer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketer',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
