# Generated by Django 3.0.4 on 2020-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0004_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi',
            name='image',
            field=models.ImageField(default='cricketer.jpg', upload_to='mi_pic'),
        ),
    ]
