# Generated by Django 3.0.4 on 2020-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0005_mi_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
        migrations.CreateModel(
            name='RCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
        migrations.CreateModel(
            name='SRH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
        migrations.AlterField(
            model_name='mi',
            name='image',
            field=models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic'),
        ),
    ]
