# Generated by Django 3.0.4 on 2020-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0006_auto_20200324_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='bid',
            field=models.IntegerField(default=5000000),
        ),
    ]
