# Generated by Django 3.0.4 on 2020-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0007_auto_20200426_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
        migrations.CreateModel(
            name='KKR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
        migrations.CreateModel(
            name='KXIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
        migrations.CreateModel(
            name='RR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketer_name', models.CharField(max_length=100)),
                ('bid', models.IntegerField(default=0)),
                ('image', models.ImageField(default='cricketer.jpg', upload_to='cricketer_pic')),
            ],
        ),
    ]
