# Generated by Django 3.0.4 on 2020-04-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketer', '0008_dc_kkr_kxip_rr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketer',
            name='slug',
        ),
    ]
